# Generated by Django 5.2.3 on 2025-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="content1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="content2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="content3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="subtitle1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="subtitle2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="subtitle3",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
