# Generated by Django 5.2.3 on 2025-07-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curriculum",
            options={"ordering": ["number"]},
        ),
    ]
