# Generated by Django 5.2.3 on 2025-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_alter_curriculum_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["number"]},
        ),
        migrations.AddField(
            model_name="category",
            name="number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
