# Generated by Django 5.2.3 on 2025-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_alter_category_options_category_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="number",
            field=models.IntegerField(),
        ),
    ]
