# Generated by Django 5.2.3 on 2025-07-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_curriculumprogress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurriculumProgress",
        ),
    ]
