# Generated by Django 5.2.3 on 2025-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0004_delete_curriculumprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="explanation",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
