# Generated by Django 5.2.3 on 2025-07-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0005_curriculum_explanation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="book_images/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_recommendations",
                        to="learn.curriculum",
                    ),
                ),
            ],
        ),
    ]
