# Generated by Django 5.2.3 on 2025-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0006_bookrecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="source",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
