# Generated by Django 5.2.3 on 2025-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_curriculum_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrecommendation",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
