# Generated by Django 5.2.3 on 2025-07-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("ox", "O/X"), ("choice", "3지선다")], max_length=10
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("choice1", models.CharField(blank=True, max_length=100, null=True)),
                ("choice2", models.CharField(blank=True, max_length=100, null=True)),
                ("choice3", models.CharField(blank=True, max_length=100, null=True)),
                ("correct_answer", models.CharField(max_length=100)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="learn.curriculum",
                    ),
                ),
            ],
        ),
    ]
