# Generated by Django 4.2.23 on 2025-07-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('concept', '개념'), ('event', '사건'), ('person', '인물'), ('history', '역사')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('ox', 'O/X'), ('choice', '3지선다')], max_length=10)),
                ('question', models.CharField(max_length=255)),
                ('choice1', models.CharField(blank=True, max_length=100, null=True)),
                ('choice2', models.CharField(blank=True, max_length=100, null=True)),
                ('choice3', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
