# Generated by Django 5.2.3 on 2025-07-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_curriculum_source"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="curriculum",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="learn.curriculum",
            ),
            preserve_default=False,
        ),
    ]
