# Generated by Django 5.2.3 on 2025-07-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_curriculum_source"),
        ("quiz", "0002_quiz_curriculum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="category",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="order",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="curriculum",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="learn.curriculum",
            ),
        ),
    ]
