# Generated by Django 5.2.3 on 2025-07-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_curriculum_source"),
        ("quiz", "0003_remove_quiz_category_remove_quiz_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="curriculum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="learn.curriculum",
            ),
        ),
    ]
