# Generated by Django 4.2.23 on 2025-07-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_category_number_alter_curriculum_number'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.curriculum', verbose_name='학습 내용'),
        ),
    ]
