# Generated by Django 4.2.23 on 2025-07-03 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=20, verbose_name='실명'),
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=128, verbose_name='학습 내용')),
                ('category', models.CharField(choices=[('concept', '개념'), ('event', '사건'), ('person', '인물'), ('history', '역사')], max_length=20)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='최초 학습일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='마지막 학습일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'content_title', 'category')},
            },
        ),
    ]
