# Generated by Django 4.2.23 on 2025-07-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_name_learningrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최초 학습일'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 학습일'),
        ),
    ]
