# Generated by Django 4.2.23 on 2025-07-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_bookrecommendation_content'),
        ('accounts', '0005_alter_learningrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learn.curriculum', verbose_name='학습 내용'),
        ),
        migrations.AlterUniqueTogether(
            name='learningrecord',
            unique_together={('user', 'curriculum', 'category')},
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='content_title',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='created_at',
        ),
    ]
