# Generated by Django 4.2.23 on 2025-07-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_bookrecommendation_content'),
        ('accounts', '0006_alter_learningrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningrecord',
            old_name='curriculum',
            new_name='content_title',
        ),
        migrations.AlterUniqueTogether(
            name='learningrecord',
            unique_together={('user', 'content_title', 'category')},
        ),
    ]
