# Generated by Django 4.2.23 on 2025-07-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_bookrecommendation_content'),
        ('accounts', '0007_rename_curriculum_learningrecord_content_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.category', verbose_name='카테고리'),
        ),
    ]
