# Generated by Django 4.2.23 on 2025-07-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_bookrecommendation_content'),
        ('accounts', '0008_alter_learningrecord_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningrecord',
            old_name='content_title',
            new_name='curriculum',
        ),
        migrations.AlterUniqueTogether(
            name='learningrecord',
            unique_together={('user', 'curriculum', 'category')},
        ),
    ]
