# Generated by Django 4.2.23 on 2025-07-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
